//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFAPhoneBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class BizContact
    {
        public int Id { get; set; }
        public System.DateTime Date_Added { get; set; }
        public string Company { get; set; }
        public string Website { get; set; }
        public string Title { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostCode { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Notes { get; set; }
    }
}
